# 01 Introduccion a NumPY

### 1. Importar libreria numpy

>>  _import numpy as np_


In [1]:
import numpy as np

### 2. crear un array de numpy

> _arr = [1,2,3,4]_ <br>
> _numpy = np.array(arr)_

In [5]:
array = [1,2,3,4]

array_np=np.array(array)

type(array_np)

numpy.ndarray

### 3.  Array bidimensional

> _bi_arr = [[1,2],[3,4],[5,6]]_ <br>
>  _np.array(bi_arr)_

In [10]:
d2_array=[
    [1,2],
    [3,4],
    [5,6]
]
bi_array=np.array(d2_array)

np.shape(bi_array)
np.shape(array_np)

(4,)

### 4. Rangos de Numeros

_print(np.arange(10))_

_print(np.arange(1,10))_

_print(np.arange(0,10,2))_

In [11]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

### 5. Vector de Ceros y Unos

_print(np.zeros(3))_

_print(np.ones(3))_

In [15]:
print(np.zeros(3))

[0. 0. 0.]


In [16]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 6. Matriz de ceros y unos
_print(np.ones((3,4)))_

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 7. Matriz Identidad
_print(np.eye(5))_

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 8. Dividir Rango en n valores

_print(np.linspace(0,10,3))_  <br>

_print(np.linspace(0,10,20))_

In [24]:
np.linspace(1,10,3)

np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

### 9. Numeros aleatorios
_print(np.random.rand(10))_

_print(np.random.rand(3,4))_

_print(np.random.randn(10))_

_print(np.random.randn(3,4))_

_print(np.random.randint(1,100,10))_

_print(np.random.randint(1,100,(2,3)))_


In [27]:
np.random.rand(10)

array([0.62836851, 0.60895524, 0.0738886 , 0.29859823, 0.52193247,
       0.63675609, 0.55946703, 0.24998129, 0.92160154, 0.46386385])

In [28]:
np.random.rand(3,4)

array([[0.10265073, 0.2389219 , 0.94466484, 0.8632831 ],
       [0.15087552, 0.02817794, 0.8661481 , 0.35152162],
       [0.45514063, 0.78042059, 0.96250887, 0.83630685]])

In [29]:
np.random.randn(10)

array([ 0.15724009, -0.27774307,  0.58831179,  0.91668403,  0.42489085,
       -0.49027189, -0.16016627,  0.53670483,  0.221272  , -1.84832574])

### 10. Numeros aleatorios con semilla

_np.random.seed(42)_

_print(np.random.rand(4))_

### 11. Reshaping Arrays
_arr = np.random.rand(2,2)_

_print(arr)_

_print(arr.shape)_

_print(arr.reshape(1,4))_

_print(arr.reshape(4,1))_




### 12. Slicing Data
_myarr = np.arange(0,11)_

_sliced = myarr[0:5]_
_print(sliced)_

_sliced[:] = 99_
_print(sliced)_

_print(myarr)_

_sliced = myarr.copy()[0:5]_

##### multi dimensional Slicing
_my_matrix = np.random.randint(1,30,(3,3))_

_print(my_matrix[0])_ 

_print(my_matrix[0][0])_

_print(my_matrix[0,0])_


### 13. Operaciones con Array
_new_arr = np.arange(1,11)_

_print(new_arr + 5)_

_print(new_arr - 5)_

_print(new_arr + new_arr)_

_print(new_arr / new_arr)_

_arr2d = np.arange(25).reshape(5,5)_

_print(arr2d.sum())_

_print(arr2d.sum(axis=0))  # sum of columns_

_print(arr2d.sum(axis=1)) #sum of rows_


### 14. Operaciones Condicionales

_arr = np.arange(0,10)_

_print(arr > 4)_

_print(arr[arr > 4])_
